# Classifying Iris Species

In [2]:
from sklearn.datasets import load_iris

In [3]:
### load_iris() return bunch object similar to dict contains key & values
dataset = load_iris()
print("Keys: ",dataset.keys())

Keys:  dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [5]:
## show value of DESCR key in length 193
print(dataset['DESCR'][:193] + "\n...")

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive att
...


In [6]:
print("target name: ",dataset['target_names'])

target name:  ['setosa' 'versicolor' 'virginica']


In [7]:
print("feature name: ",dataset['feature_names'])

feature name:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [13]:
## show type of data
print("type of data: ",type(dataset['data']))
## shape of data
print("shape ",dataset['data'].shape)

type of data:  <class 'numpy.ndarray'>
shape  (150, 4)


In [10]:
## first 5 col
print("first 5 col: ",dataset['data'][:5])

first 5 col:  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [16]:
## type of target
print("type of target: ",type(dataset['target']))
## shape of target
print("shape of target: ",dataset['target'].shape)
print("target: \n",dataset['target'])
## 0 = setosa, 1=versicolor, 3=virginica

type of target:  <class 'numpy.ndarray'>
shape of target:  (150,)
target: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
